# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d914281fd59bd93455cfdfd608db96bd82f4eb5ea4bfe118777791cb8583681254c924e07828e2cd62f0588b600e440542f5218f004455545afca53061236223

test:
  secret_key_base: 775f7f4d28d315e64b18ef40beb20bf8012c65eccf65923bae6990550f3abc1b40acb481def4311e6dfb4ef35e0655dfe01382f9a74a2878cc062b7c4cbc8546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
